# project practice

## case1: Real Estate Market Insights and Valuation
房地产市场洞察与价值评估

### 1. 导入库

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

plt.rcParams['font.sans-serif'] = ['SimHei']

### 2. 导入数据

In [2]:
df = pd.read_csv('../data/house_sales.csv')

### 3. 数据概览

In [3]:
print('总记录数：', len(df))
print('字段数量：', len(df.columns))
display(df.head())
df.info()

总记录数： 106118
字段数量： 12

,city,address,area,floor,name,price,province,rooms,toward,unit,year,origin_url
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建,https://hf.esf.fang.com/chushou/3_404230646.htm
1,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建,https://hf.esf.fang.com/chushou/3_404230646.htm
2,合肥,生态公园-淮海大道与大众路交口,95㎡,中层（共18层）,正荣·悦都荟,132万,安徽,3室2厅,南向,13895元/㎡,2019年建,https://hf.esf.fang.com/chushou/3_404304901.htm
3,合肥,生态公园-淮海大道与大众路交口,95㎡,中层（共18层）,正荣·悦都荟,132万,安徽,3室2厅,南向,13895元/㎡,2019年建,https://hf.esf.fang.com/chushou/3_404304901.htm
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37㎡,中层（共22层）,文一名门金隅,32万,安徽,2室1厅,南北向,8649元/㎡,2017年建,https://hf.esf.fang.com/chushou/3_404372096.htm

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106118 entries, 0 to 106117
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   city        106118 non-null  object
 1   address     104452 non-null  object
 2   area        105324 non-null  object
 3   floor       104024 non-null  object
 4   name        105564 non-null  object
 5   price       105564 non-null  object
 6   province    106118 non-null  object
 7   rooms       104036 non-null  object
 8   toward      105240 non-null  object
 9   unit        105564 non-null  object
 10  year        57736 non-null   object
 11  origin_url  105564 non-null  object
dtypes: object(12)
memory usage: 9.7+ MB

### 4. 数据清洗

#### 4.1 缺失值处理

In [4]:
# 删除无用的列
df.drop(columns=['origin_url'], inplace=True)
display(df.head())

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建
1,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建
2,合肥,生态公园-淮海大道与大众路交口,95㎡,中层（共18层）,正荣·悦都荟,132万,安徽,3室2厅,南向,13895元/㎡,2019年建
3,合肥,生态公园-淮海大道与大众路交口,95㎡,中层（共18层）,正荣·悦都荟,132万,安徽,3室2厅,南向,13895元/㎡,2019年建
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37㎡,中层（共22层）,文一名门金隅,32万,安徽,2室1厅,南北向,8649元/㎡,2017年建

In [5]:
# 检查是否有缺失值
display(df.isna().sum())

# 删除缺失值
df.dropna(inplace=True)

city            0
address      1666
area          794
floor        2094
name          554
price         554
province        0
rooms        2082
toward        878
unit          554
year        48382
dtype: int64

In [6]:
print('去除空值后的记录数：', len(df))

去除空值后的记录数： 57520

#### 4.2 重复值处理

In [7]:
# 检查是否有重复值
display(df.duplicated().sum())

# 删除重复数据
df.drop_duplicates(inplace=True)

np.int64(29416)

In [8]:
print('数据清洗后的数据记录数：', len(df))

数据清洗后的数据记录数： 28104

In [9]:
display(df.head())

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建
2,合肥,生态公园-淮海大道与大众路交口,95㎡,中层（共18层）,正荣·悦都荟,132万,安徽,3室2厅,南向,13895元/㎡,2019年建
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37㎡,中层（共22层）,文一名门金隅,32万,安徽,2室1厅,南北向,8649元/㎡,2017年建
6,合肥,龙岗-长江东路与和县里交口,50㎡,高层（共30层）,柏庄金座,46万,安徽,2室1厅,南向,9200元/㎡,2019年建
8,合肥,新亚汽车站-张洼路与临泉路交汇处向北100米(原红星机械,120㎡,中层（共27层）,天目未来,158万,安徽,4室2厅,南向,13167元/㎡,2012年建

#### 4.3 数据类型转换

In [10]:
# area 的数据类型转换
df['area'] = df['area'].str.replace('㎡', '').astype(float)

In [11]:
# price 的数据类型转换
df['price'] = df['price'].str.replace('万', '').astype(float)

In [12]:
# toward 的数据类型转换
display(df['toward'].value_counts())
df['toward'] = df['toward'].astype('category')

toward
南北向    15946
南向      9405
东南向     1114
东向       448
西南向      308
北向       276
西向       182
东西向      162
西北向      138
东北向      125
Name: count, dtype: int64

In [13]:
# unit 的数据类型转换
df['unit'] = df['unit'].str.replace('元/㎡', '').astype('float')

In [14]:
# year 的数据类型转换
df['year'] = df['year'].str.replace('年建', '').astype(int)

In [15]:
display(df.head())
df.info()

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90.0,中层（共18层）,圣地亚哥,128.0,安徽,3室2厅,南北向,14222.0,2013
2,合肥,生态公园-淮海大道与大众路交口,95.0,中层（共18层）,正荣·悦都荟,132.0,安徽,3室2厅,南向,13895.0,2019
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37.0,中层（共22层）,文一名门金隅,32.0,安徽,2室1厅,南北向,8649.0,2017
6,合肥,龙岗-长江东路与和县里交口,50.0,高层（共30层）,柏庄金座,46.0,安徽,2室1厅,南向,9200.0,2019
8,合肥,新亚汽车站-张洼路与临泉路交汇处向北100米(原红星机械,120.0,中层（共27层）,天目未来,158.0,安徽,4室2厅,南向,13167.0,2012

<class 'pandas.core.frame.DataFrame'>
Index: 28104 entries, 0 to 106088
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   city      28104 non-null  object
 1   address   28104 non-null  object
 2   area      28104 non-null  float64
 3   floor     28104 non-null  object
 4   name      28104 non-null  object
 5   price     28104 non-null  float64
 6   province  28104 non-null  object
 7   rooms     28104 non-null  object
 8   toward    28104 non-null  category
 9   unit      28104 non-null  float64
 10  year      28104 non-null  int64
dtypes: category(1), float64(3), int64(1), object(6)
memory usage: 2.4+ MB

#### 4.4 异常值处理

In [16]:
# 房屋面积 area 异常值处理
# display(df[df['area'] < 20])
# display(df[df['area'] > 600])

display(len(df[(df['area'] > 20) & (df['area'] < 600)]))

df = df[(df['area'] > 20) & (df['area'] < 600)]

28079

In [17]:
# 房屋售价 price 的异常值处理 IQR
Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)
IQR = Q3 - Q1
high_price = Q3 + 1.5 * IQR
low_price = Q1 - 1.5 * IQR
# display(df[df['price'] < low_price])
# display(df[df['price'] > high_price])
display(len(df[(df['price'] < high_price) & (df['price'] > low_price)]))
df = df[(df['price'] < high_price) & (df['price'] > low_price)]

26135

### 5. 新数据特征构造

In [18]:
display(df.head())

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90.0,中层（共18层）,圣地亚哥,128.0,安徽,3室2厅,南北向,14222.0,2013
2,合肥,生态公园-淮海大道与大众路交口,95.0,中层（共18层）,正荣·悦都荟,132.0,安徽,3室2厅,南向,13895.0,2019
4,合肥,撮镇-文一名门金隅裕溪路与东风大道交口,37.0,中层（共22层）,文一名门金隅,32.0,安徽,2室1厅,南北向,8649.0,2017
6,合肥,龙岗-长江东路与和县里交口,50.0,高层（共30层）,柏庄金座,46.0,安徽,2室1厅,南向,9200.0,2019
8,合肥,新亚汽车站-张洼路与临泉路交汇处向北100米(原红星机械,120.0,中层（共27层）,天目未来,158.0,安徽,4室2厅,南向,13167.0,2012

In [19]:
# 地区 district
display(df['address'].str.split('-').str[0])
df['district'] = df['address'].str.split('-').str[0]

0            龙岗
2          生态公园
4            撮镇
6            龙岗
8         新亚汽车站
          ...
106080     万达广场
106082     万达广场
106084     万达广场
106086     利州广场
106088     永隆百货
Name: address, Length: 26135, dtype: object

In [20]:
# 楼层类型 floor_type
# display(df['floor'].str.split('（').str[0])
# df['floor_type'] = df['floor'].str.split('（').str[0].astype('category')

def func1(s):
    if pd.isna(s):
        return '未知'
    elif '低' in s:
        return '低楼层'
    elif '中' in s:
        return '中楼层'
    elif '高' in s:
        return '高楼层'
    else:
        return '未知'

display(df['floor'].apply(func=func1))
df['floor_type'] = df['floor'].apply(func=func1).astype('category')

0         中楼层
2         中楼层
4         中楼层
6         高楼层
8         中楼层
         ...
106080    中楼层
106082    中楼层
106084    高楼层
106086    低楼层
106088    低楼层
Name: floor, Length: 26135, dtype: object

In [21]:
# 是否是直辖市 is_municipality
# def func2(s):
#     if s in ['北京', '上海', '重庆', '天津']:
#         return 1
#     else:
#         return 0
# display(df['city'].apply(func=func2))
# df['is_municipality'] = df['city'].apply(func=func2)

# display(df['city'].apply(lambda x: 1 if x in ['北京', '上海', '重庆', '天津'] else 0))
# df['is_municipality'] = df['city'].apply(lambda x: 1 if x in ['北京', '上海', '重庆', '天津'] else 0)

display(df['city'].isin(['北京', '上海', '重庆', '天津']).astype(int))
df['is_municipality'] = df['city'].isin(['北京', '上海', '重庆', '天津']).astype(int)

# display(df['province'].isin(['直辖市']).astype(int))
# df['is_municipality'] = df['province'].isin(['直辖市']).astype(int)

# display((df['province'] == '直辖市').astype(int))
# df['is_municipality'] = (df['province'] == '直辖市').astype(int)

0         0
2         0
4         0
6         0
8         0
         ..
106080    0
106082    0
106084    0
106086    0
106088    0
Name: city, Length: 26135, dtype: int64

In [22]:
# 卧室数量 bedroom_count
# display(df['rooms'].str.split('室').str[0].astype(int))
# df['bedroom_count'] = df['rooms'].str.split('室').str[0].astype(int)

display(df['rooms'].str.extract(r'(\d+)室').astype(int))
df['bedroom_count'] = df['rooms'].str.extract(r'(\d+)室').astype(int)

        0
0       3
2       3
4       2
6       2
8       4
...    ..
106080  2
106082  2
106084  2
106086  2
106088  2

[26135 rows x 1 columns]

In [23]:
# 客厅数量 living_room_count
# display(df['rooms'].str.split('室').str[1].str.split('厅').str[0].astype(int))
# df['living_room_count'] = df['rooms'].str.split('室').str[1].str.split('厅').str[0].astype(int)

display(df['rooms'].str.extract(r'(\d+)厅').astype(int))
df['living_room_count'] = df['rooms'].str.extract(r'(\d+)厅').astype(int)

        0
0       2
2       2
4       1
6       1
8       2
...    ..
106080  2
106082  2
106084  1
106086  2
106088  2

[26135 rows x 1 columns]

In [24]:
# 楼龄 building_age
df['building_age'] = 2026 - df['year']

In [25]:
# 价格分段 price_segment
display(pd.cut(df['price'], bins=4, labels=['低价', '中价', '高价', '豪华']))
df['price_segment'] = pd.cut(df['price'], bins=4, labels=['低价', '中价', '高价', '豪华'])

0         中价
2         中价
4         低价
6         低价
8         高价
          ..
106080    低价
106082    低价
106084    低价
106086    中价
106088    低价
Name: price, Length: 26135, dtype: category
Categories (4, object): ['低价' < '中价' < '高价' < '豪华']

In [26]:
display(df.sample(5))
display(df.info())
df['is_municipality'].value_counts()

,city,address,area,floor,name,price,province,rooms,toward,unit,year,district,floor_type,is_municipality,bedroom_count,living_room_count,building_age,price_segment
17678,法库,会展中心-银杏路28号(体育学院对面),84.0,高层（共33层）,华府丹郡·乾豪,70.0,辽宁,2室2厅,南北向,8333.0,2016,会展中心,高楼层,0,2,2,10,低价
12470,舞钢,建设西路-建设路与光明路交汇处,72.0,中层（共6层）,蓝鲸国际,45.0,河南,2室2厅,西向,6250.0,1995,建设西路,中楼层,0,2,2,31,低价
93424,南充,市政新区-颐和嘉园西区9栋2单元0101,185.0,高层（共6层）,颐和嘉园西区,123.0,四川,4室2厅,南向,6649.0,2013,市政新区,高楼层,0,4,2,13,中价
78710,温岭,"东商务区-台州大道东侧,体育场路南侧",125.0,中层（共16层）,绿城海棠花苑,240.0,浙江,3室2厅,南向,19200.0,2015,东商务区,中楼层,0,3,2,11,豪华
34146,武汉,古田-华润翡翠城古田二路与城华路交汇处(园博园西入,97.0,低层（共33层）,华润翡翠城,138.0,湖北,3室2厅,南北向,14227.0,2017,古田,低楼层,0,3,2,9,中价

<class 'pandas.core.frame.DataFrame'>
Index: 26135 entries, 0 to 106088
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   city               26135 non-null  object
 1   address            26135 non-null  object
 2   area               26135 non-null  float64
 3   floor              26135 non-null  object
 4   name               26135 non-null  object
 5   price              26135 non-null  float64
 6   province           26135 non-null  object
 7   rooms              26135 non-null  object
 8   toward             26135 non-null  category
 9   unit               26135 non-null  float64
 10  year               26135 non-null  int64
 11  district           26135 non-null  object
 12  floor_type         26135 non-null  category
 13  is_municipality    26135 non-null  int64
 14  bedroom_count      26135 non-null  int64
 15  living_room_count  26135 non-null  int64
 16  building_age       26135 non-null  int64
 17  price_segment      26135 non-null  category
dtypes: category(3), float64(3), int64(5), object(7)
memory usage: 3.3+ MB

None

is_municipality
0    25905
1      230
Name: count, dtype: int64

### 6. 问题分析及可视化