# DataFrame 案例分析

## 案例 1 ：学生成绩分析
场景：某班级的学生成绩如下，请完成如下任务：

- 计算每位学生的总分和平均分
- 找出数学成绩高于 90 分或英语成绩高于 85 分的学生
- 按总分从高到低排序，并输出前三名学生

In [1]:
import pandas as pd
data = {
        '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
        '数学': [82, 92, 78, 88, 95],
        '英语': [98, 88, 85, 92, 80],
        '物理': [75, 80, 88, 85, 90]
    }

In [2]:
scores = pd.DataFrame(data)
scores

   姓名  数学  英语  物理
0  张三  82  98  75
1  李四  92  88  80
2  王五  78  85  88
3  赵六  88  92  85
4  钱七  95  80  90

In [3]:
scores['总分'] = scores[['数学', '英语', '物理']].sum(axis=1)
# scores['平均分'] = scores['总分'] / 3
scores['平均分'] = scores[['数学', '英语', '物理']].mean(axis=1)
scores

   姓名  数学  英语  物理   总分        平均分
0  张三  82  98  75  255  85.000000
1  李四  92  88  80  260  86.666667
2  王五  78  85  88  251  83.666667
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333

In [4]:
scores[(scores['数学'] > 90) | (scores['英语'] > 85)]

   姓名  数学  英语  物理   总分        平均分
0  张三  82  98  75  255  85.000000
1  李四  92  88  80  260  86.666667
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333

In [5]:
print(scores.sort_values(by='总分', ascending=False).head(3))
print(scores.nlargest(3, columns='总分'))

   姓名  数学  英语  物理   总分        平均分
4  钱七  95  80  90  265  88.333333
3  赵六  88  92  85  265  88.333333
1  李四  92  88  80  260  86.666667
   姓名  数学  英语  物理   总分        平均分
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333
1  李四  92  88  80  260  86.666667

## 案例 2： 销售数据分析
场景：某公司的销售数据如下，请完成如下任务：

- 计算每种产品的总销售额（销售额 = 单价 * 销量）
- 找出销售额最高的产品
- 按销售额从高到低排序，输出所有产品信息

In [6]:
import pandas as pd
data = {
    '产品名称': ['A', 'B', 'C', 'D'],
    '单价': [100, 150, 200, 120],
    '销量': [50, 30, 20, 40]
}

In [7]:
df = pd.DataFrame(data)
df

  产品名称   单价  销量
0    A  100  50
1    B  150  30
2    C  200  20
3    D  120  40

In [8]:
df['销售额'] =  df['单价'] * df['销量']
df

  产品名称   单价  销量   销售额
0    A  100  50  5000
1    B  150  30  4500
2    C  200  20  4000
3    D  120  40  4800

In [9]:
df.nlargest(1, columns='销售额')

  产品名称   单价  销量   销售额
0    A  100  50  5000

In [10]:
df.sort_values(by=['销售额'], ascending=False)

  产品名称   单价  销量   销售额
0    A  100  50  5000
3    D  120  40  4800
1    B  150  30  4500
2    C  200  20  4000

## 案例 3 ：电商用户行为分析
某电商的用户行为数据如下， 请完成以下任务：

- 计算每位用户的总消费金额 (消费金额 = 商品单价 * 购买数量)
- 找出消费金额最高的用户并输出所有信息
- 计算所有用户的平均消费金额（保留两位小数）
- 统计电子产品的总购买数量

In [11]:
import pandas as pd
data = {
    '用户ID': [101, 102, 103, 104, 105],
    '用户名': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    '商品类别': ['电子产品', '服饰', '电子产品', '家居', '服饰'],
    '商品单价': [1200, 300, 800, 150, 200],
    '购买数量': [1, 3, 2, 5, 4]
}

In [12]:
df = pd.DataFrame(data)
df

   用户ID      用户名  商品类别  商品单价  购买数量
0   101    Alice  电子产品  1200     1
1   102      Bob    服饰   300     3
2   103  Charlie  电子产品   800     2
3   104    David    家居   150     5
4   105      Eve    服饰   200     4

In [13]:
df['总消费金额'] = df['商品单价'] * df['购买数量']
df

   用户ID      用户名  商品类别  商品单价  购买数量  总消费金额
0   101    Alice  电子产品  1200     1   1200
1   102      Bob    服饰   300     3    900
2   103  Charlie  电子产品   800     2   1600
3   104    David    家居   150     5    750
4   105      Eve    服饰   200     4    800

In [14]:
df.nlargest(1, columns='总消费金额')

   用户ID      用户名  商品类别  商品单价  购买数量  总消费金额
2   103  Charlie  电子产品   800     2   1600

In [15]:
print('平均消费金额：%.2f' % df['总消费金额'].mean())

平均消费金额：1050.00

In [16]:
print(df[df['商品类别'] == '电子产品']['购买数量'].sum())

3