# DataFrame
## 01 DataFrame 的创建方式

In [1]:
import numpy as np
import pandas as pd
from pandas.core.algorithms import nunique_ints

In [17]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])
df = pd.DataFrame({'第一列': s1, '第二列': s2})
# print(type(df['第一列']))
# 通过字典创建
df = pd.DataFrame(
    {
       'name': ['tom', 'jack', 'alice', 'bob', 'allen'],
        'age': [15, 17, 20, 26, 30],
        'score': [60.5, 80, 30.6, 70, 83.6]
    }, index=[1, 2, 3, 4, 5], columns=['name', 'score', 'age']
)
df

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.6   30

## 02 DataFrame 的属性

In [18]:
# DataFrame 的属性
print('行索引：')
print(df.index)
print('列标签：')
print(df.columns)
print('值：')
print(df.values)

行索引：
Index([1, 2, 3, 4, 5], dtype='int64')
列标签：
Index(['name', 'score', 'age'], dtype='object')
值：
[['tom' 60.5 15]
 ['jack' 80.0 17]
 ['alice' 30.6 20]
 ['bob' 70.0 26]
 ['allen' 83.6 30]]

In [27]:
print('维度：', df.ndim)
print('形状：', df.shape)
print('元素个数：', df.size)
print('数据类型：')
print(df.dtypes)

维度： 2
形状： (5, 3)
元素个数： 15
数据类型：
name      object
score    float64
age        int64
dtype: object

In [30]:
# 行列转置
print('行列转置：')
print(df.T)
print(df.T.index)
print(df.T.columns)

行列转置：
          1     2      3     4      5
name    tom  jack  alice   bob  allen
score  60.5  80.0   30.6  70.0   83.6
age      15    17     20    26     30
Index(['name', 'score', 'age'], dtype='object')
Index([1, 2, 3, 4, 5], dtype='int64')

In [31]:
print(df)

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.6   30

In [38]:
# 获取元素 loc iloc at iat
# 获取某行
print(df.loc[4, :])
print(df.iloc[3, :])

# 获取某列
print(df.loc[:, 'name'])
print(df.iloc[:, 0])

name      bob
score    70.0
age        26
Name: 4, dtype: object
name      bob
score    70.0
age        26
Name: 4, dtype: object
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object

In [41]:
# 获取单个数据
print(df.at[3, 'score'])
print(df.loc[3, 'score'])
print(df.iat[2, 1])
print(df.iloc[2, 1])

30.6
30.6
30.6
30.6

## 03 DataFrame 数据访问

In [53]:
# 获取当列数据, df[列标签]
print(df['name'])
print(type(df['name']))
print(df.name)
print(type(df.name))
print(df[['name']])
print(type(df[['name']]))
df[['name', 'score']]

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
<class 'pandas.core.series.Series'>
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
<class 'pandas.core.series.Series'>
    name
1    tom
2   jack
3  alice
4    bob
5  allen
<class 'pandas.core.frame.DataFrame'>

    name  score
1    tom   60.5
2   jack   80.0
3  alice   30.6
4    bob   70.0
5  allen   83.6

In [56]:
print(df[['name', 'score']]) # 多列数据的获取，返回 DataFrame

    name  score
1    tom   60.5
2   jack   80.0
3  alice   30.6
4    bob   70.0
5  allen   83.6

In [58]:
# 查看部分数据
print(df.head(3))

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20

In [59]:
print(df.tail(2))

    name  score  age
4    bob   70.0   26
5  allen   83.6   30

In [67]:
# 使用布尔索引筛选数据
print(df[df.score > 70])
print(df[(df.age > 20) & (df.score > 70.0)])
df[(df['age'] > 20) & (df['score'] > 70.0)]

    name  score  age
2   jack   80.0   17
5  allen   83.6   30
    name  score  age
5  allen   83.6   30

    name  score  age
5  allen   83.6   30

In [71]:
# 随机取样
df.sample(3)

    name  score  age
5  allen   83.6   30
4    bob   70.0   26
1    tom   60.5   15

## 04 DataFrame 的常用方法

In [73]:
print(df.head()) # 查看前 n 行数据，默认前 5 行
print(df.tail(1)) # 查看后 n 行数据，默认后 5 行

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.6   30
    name  score  age
5  allen   83.6   30

In [76]:
print(df.isin(['jack'])) # 查看每个元素是否在参数集合中
print(df.isin(['jack', 20]))

    name  score    age
1  False  False  False
2   True  False  False
3  False  False  False
4  False  False  False
5  False  False  False
    name  score    age
1  False  False  False
2   True  False  False
3  False  False   True
4  False  False  False
5  False  False  False

In [79]:
print(df.isna()) # 查看每个元素是否是缺失值

    name  score    age
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False

In [91]:
print(df['age'].sum()) # 求某一列的总和
print(df['score'].max()) # 最大值
print(df['age'].min()) # 最小值
print(df['score'].mean()) # 平均值
print(df['score'].median()) # 中位数
print(df['score'].mode()) # 众数
print(df['age'].mode())

108
83.6
15
64.94
70.0
0    30.6
1    60.5
2    70.0
3    80.0
4    83.6
Name: score, dtype: float64
0    15
1    17
2    20
3    26
4    30
Name: age, dtype: int64

In [94]:
df = pd.DataFrame(
    {
       'name': ['tom', 'jack', 'alice', 'bob', 'allen'],
        'age': [15, 15, 20, 26, 30],
        'score': [60.5, 80, 30.6, 70, 83.6]
    }, index=[1, 2, 3, 4, 5], columns=['name', 'score', 'age']
)
print(df['age'].mode()) # 众数

0    15
Name: age, dtype: int64

In [101]:
print(df.score.std()) # 标准差
print(df.score.var()) # 方差
print(df.score.quantile(0.25))

21.210563406001263
449.8879999999999
60.5

In [103]:
print(df.describe())

           score        age
count   5.000000   5.000000
mean   64.940000  21.200000
std    21.210563   6.685806
min    30.600000  15.000000
25%    60.500000  15.000000
50%    70.000000  20.000000
75%    80.000000  26.000000
max    83.600000  30.000000

In [104]:
print(df.count())

name     5
score    5
age      5
dtype: int64

In [131]:
df = pd.DataFrame(
    {
       'name': ['tom', 'tom','jack', 'alice', 'bob', 'allen'],
        'age': [15, 15, 15, 20, 26, 30],
        'score': [60.5, 60.5,  80, 30.6, 70, 83.6]
    }, index=[1, 2, 3, 4, 5, 6], columns=['name', 'age', 'score']
)
print(df.value_counts()) # 每条记录出现的次数
print(df.nunique())

name   age  score
tom    15   60.5     2
alice  20   30.6     1
allen  30   83.6     1
bob    26   70.0     1
jack   15   80.0     1
Name: count, dtype: int64
name     5
age      4
score    5
dtype: int64

In [125]:
print(df.drop_duplicates())

    name  age  score
1    tom   15   60.5
3   jack   15   80.0
4  alice   20   30.6
5    bob   26   70.0
6  allen   30   83.6

In [134]:
print(df.duplicated())
print(df.duplicated(subset=['age'])) # 查看是否重复

1    False
2     True
3    False
4    False
5    False
6    False
dtype: bool
1    False
2     True
3     True
4    False
5    False
6    False
dtype: bool

In [128]:
df.sample(3) # 随机抽样

    name  age  score
4  alice   20   30.6
1    tom   15   60.5
2    tom   15   60.5

In [129]:
print(df.replace(15, 30))

    name  age  score
1    tom   30   60.5
2    tom   30   60.5
3   jack   30   80.0
4  alice   20   30.6
5    bob   26   70.0
6  allen   30   83.6

In [135]:
# 累计和 累积积
df

    name  age  score
1    tom   15   60.5
2    tom   15   60.5
3   jack   15   80.0
4  alice   20   30.6
5    bob   26   70.0
6  allen   30   83.6

In [144]:
df.cumsum() # 累积和
df.cumsum(axis=0) # 默认 axis=0 表示按列累积

                      name  age  score
1                      tom   15   60.5
2                   tomtom   30  121.0
3               tomtomjack   45  201.0
4          tomtomjackalice   65  231.6
5       tomtomjackalicebob   91  301.6
6  tomtomjackaliceboballen  121  385.2

In [139]:
df.cummax()

  name  age  score
1  tom   15   60.5
2  tom   15   60.5
3  tom   15   80.0
4  tom   20   80.0
5  tom   26   80.0
6  tom   30   83.6

In [141]:
df.cummin()

    name  age  score
1    tom   15   60.5
2    tom   15   60.5
3   jack   15   60.5
4  alice   15   30.6
5  alice   15   30.6
6  alice   15   30.6

In [146]:
print(df.sort_index(ascending=False)) # 按索引从大到小排序

    name  age  score
6  allen   30   83.6
5    bob   26   70.0
4  alice   20   30.6
3   jack   15   80.0
2    tom   15   60.5
1    tom   15   60.5

In [149]:
print(df.sort_values(by='name')) # 按照列排序

    name  age  score
4  alice   20   30.6
6  allen   30   83.6
5    bob   26   70.0
3   jack   15   80.0
1    tom   15   60.5
2    tom   15   60.5

In [152]:
df = pd.DataFrame(
    {
       'name': ['tom', 'tom','jack', 'alice', 'bob', 'allen'],
        'age': [15, 15, 15, 20, 26, 30],
        'score': [60.5, 60.5,  80, 30.6, 70, 80]
    }, index=[1, 2, 3, 4, 5, 6], columns=['name', 'score', 'age']
)

In [153]:
print(df.sort_values(by='score'))

    name  score  age
4  alice   30.6   20
1    tom   60.5   15
2    tom   60.5   15
5    bob   70.0   26
3   jack   80.0   15
6  allen   80.0   30

In [156]:
print(df.sort_values(by=['score', 'age'], ascending=[True, False])) # 按照多列排序

    name  score  age
4  alice   30.6   20
1    tom   60.5   15
2    tom   60.5   15
5    bob   70.0   26
6  allen   80.0   30
3   jack   80.0   15

In [165]:
print(df.nlargest(2, columns=['score', 'age'])) # 最大几个值

    name  score  age
6  allen   80.0   30
3   jack   80.0   15

In [164]:
print(df.nsmallest(2, columns=['score', 'age']))

    name  score  age
4  alice   30.6   20
1    tom   60.5   15