# pandas 综合案例

## 01 企鹅体重分析

In [1]:
# 一般步骤：
    # 1. 导入一些必要的库
    # 2. 导入数据
    # 3. 数据清洗
    # 4. 数据特征的构造
    # 5. 数据分析

In [2]:
# 1. 导入一些必要的库
import pandas as pd

In [3]:
# 2. 导入数据
df = pd.read_csv('../data/penguins.csv')

In [4]:
df.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [6]:
# 3. 数据清洗
df.isna().sum(axis=0)

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
df.isna().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 333 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            333 non-null    object
 1   island             333 non-null    object
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    float64
 5   body_mass_g        333 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 20.8+ KB

In [10]:
# 4. 数据特征的构造
df.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

In [11]:
df['sex'] = df['sex'].astype('category')

In [12]:
df['bill_radio'] = df['bill_length_mm'] / df['bill_depth_mm']

In [13]:
df.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_radio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.090909
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270115
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.238889
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.901554
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.907767

In [14]:
# 5. 数据分析
# 数据分箱：体重分为3个等级
labels = ['低', '中', '高']
df['body_level'] = pd.cut(df['body_mass_g'], bins=3, labels=labels)

In [15]:
df['body_level'].value_counts()

body_level
低    150
中    128
高     55
Name: count, dtype: int64

In [16]:
# 分组：按岛屿和性别分组分析
df.groupby(['sex'], observed=False).agg({
    'body_mass_g': ['mean', 'median', 'count']
})

        body_mass_g
               mean  median count
sex
Female  3862.272727  3650.0   165
Male    4545.684524  4300.0   168

In [17]:
df.groupby(['island'], observed=False).agg({
    'body_mass_g': ['mean', 'median', 'count']
})

           body_mass_g
                  mean  median count
island
Biscoe     4719.171779  4800.0   163
Dream      3718.902439  3700.0   123
Torgersen  3708.510638  3700.0    47

## 案例 2 ：睡眠质量分析

In [25]:
# 1. 导入必要的库
import pandas as pd
import numpy as np

In [26]:
# 2. 导入数据
df = pd.read_csv('../data/sleep.csv')

In [27]:
df.head(5)

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                400 non-null    int64
 1   gender                   400 non-null    object
 2   age                      400 non-null    int64
 3   occupation               400 non-null    object
 4   sleep_duration           400 non-null    float64
 5   sleep_quality            400 non-null    float64
 6   physical_activity_level  400 non-null    int64
 7   stress_level             400 non-null    int64
 8   bmi_category             400 non-null    object
 9   blood_pressure           400 non-null    object
 10  heart_rate               400 non-null    int64
 11  daily_steps              400 non-null    int64
 12  sleep_disorder           110 non-null    object
dtypes: float64(2), int64(6), object(5)
memory usage: 40.8+ KB

In [29]:
df.describe()

,person_id,age,sleep_duration,sleep_quality,physical_activity_level,stress_level,heart_rate,daily_steps
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.00000,400.000000,400.000000
mean,200.500000,39.950000,8.041250,6.125750,64.985000,5.47250,75.990000,11076.510000
std,115.614301,14.038883,2.390787,1.975733,32.297874,2.80873,15.099334,5364.789364
min,1.000000,18.000000,4.100000,1.000000,10.000000,1.00000,50.000000,2067.000000
25%,100.750000,29.000000,5.900000,4.700000,35.000000,3.00000,63.000000,6165.250000
50%,200.500000,40.000000,8.200000,6.100000,65.500000,5.00000,77.000000,11785.500000
75%,300.250000,49.000000,10.125000,7.425000,94.000000,8.00000,90.000000,15878.000000
max,400.000000,90.000000,12.000000,10.000000,120.000000,10.00000,100.000000,19958.000000

In [32]:
# 3. 数据清洗
df.isna().sum()

person_id                    0
gender                       0
age                          0
occupation                   0
sleep_duration               0
sleep_quality                0
physical_activity_level      0
stress_level                 0
bmi_category                 0
blood_pressure               0
heart_rate                   0
daily_steps                  0
sleep_disorder             290
dtype: int64

In [33]:
df.drop(columns='sleep_disorder', inplace=True)

In [34]:
df.isna().sum()

person_id                  0
gender                     0
age                        0
occupation                 0
sleep_duration             0
sleep_quality              0
physical_activity_level    0
stress_level               0
bmi_category               0
blood_pressure             0
heart_rate                 0
daily_steps                0
dtype: int64

In [36]:
df

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945
...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079

In [37]:
# 4. 数据特征构造
df['gender'] = df['gender'].astype('category')

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                400 non-null    int64
 1   gender                   400 non-null    category
 2   age                      400 non-null    int64
 3   occupation               400 non-null    object
 4   sleep_duration           400 non-null    float64
 5   sleep_quality            400 non-null    float64
 6   physical_activity_level  400 non-null    int64
 7   stress_level             400 non-null    int64
 8   bmi_category             400 non-null    object
 9   blood_pressure           400 non-null    object
 10  heart_rate               400 non-null    int64
 11  daily_steps              400 non-null    int64
dtypes: category(1), float64(2), int64(6), object(3)
memory usage: 35.0+ KB

In [39]:
df['occupation'].value_counts()

occupation
Student          110
Office Worker     99
Manual Labor      96
Retired           95
Name: count, dtype: int64

In [40]:
df['occupation'] = df['occupation'].astype('category')

In [41]:
df['bmi_category'] = df['bmi_category'].astype('category')

In [42]:
df['blood_pressure'].str.split('/', expand=True)

       0   1
0    124  70
1    131  86
2    122  70
3    124  72
4    133  78
..   ...  ..
395  118  66
396  132  80
397  125  76
398  130  75
399  118  70

[400 rows x 2 columns]

In [43]:
df[['high', 'low']] = df['blood_pressure'].str.split('/', expand=True)

In [44]:
df

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,high,low
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,124,70
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,131,86
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,122,70
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,124,72
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,133,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497,118,66
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848,132,80
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255,125,76
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567,130,75
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079,118,70

In [46]:
# 睡眠质量分箱
labels = ['差', '中', '优']
df['quality_level'] = pd.cut(df['sleep_quality'], bins=3, labels=labels)

In [47]:
df

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,high,low,quality_level
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,124,70,中
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,131,86,中
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,122,70,中
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,124,72,优
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,133,78,优
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497,118,66,优
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848,132,80,中
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255,125,76,中
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567,130,75,优
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079,118,70,中

In [49]:
age_labels = ['青少年', '中年', '老年']
df['age_level'] = pd.cut(df['age'], bins=3, labels=age_labels)

In [50]:
df

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,high,low,quality_level,age_level
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,124,70,中,青少年
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,131,86,中,中年
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,122,70,中,中年
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,124,72,优,青少年
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,133,78,优,老年
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497,118,66,优,青少年
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848,132,80,中,中年
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255,125,76,中,青少年
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567,130,75,优,青少年
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079,118,70,中,青少年

In [52]:
# 5. 数据统计与分析
df['bmi_category'].value_counts()

bmi_category
Overweight     109
Underweight    102
Obese           98
Normal          91
Name: count, dtype: int64

In [57]:
# 根据不同的 bmi 分组分析
df.groupby(['age_level', 'bmi_category'], observed=False).agg({
    'sleep_duration': 'mean',
    'sleep_quality': 'mean',
    'stress_level': 'mean'
})

                        sleep_duration  sleep_quality  stress_level
age_level bmi_category
青少年       Normal              8.100000       6.332000      4.860000
          Obese               8.250000       6.253448      5.534483
          Overweight          8.214286       6.171429      5.317460
          Underweight         7.603279       5.883607      5.426230
中年        Normal              7.422222       6.650000      4.944444
          Obese               7.805556       6.216667      5.888889
          Overweight          8.246154       5.956410      5.974359
          Underweight         8.497500       5.907500      5.750000
老年        Normal              7.420000       4.240000      4.200000
          Obese               7.900000       5.025000      8.000000
          Overweight          8.971429       6.285714      6.714286
          Underweight        10.500000       6.200000      6.000000