# data analysis learning
## 01 数据预处理
### 01 数据导入和导出

In [1]:
# 数据导入
import pandas as pd

df = pd.read_csv('../data/employees.csv')
print(type(df))
print(df.head())
print(df.salary.mean())
# 数据导出
df = df.tail()
df.to_csv('../data/new.csv')

<class 'pandas.core.frame.DataFrame'>
   employee_id first_name last_name     email  phone_number   job_id   salary  \
0          100     Steven      King     SKING  515.123.4567  AD_PRES  24000.0
1          101      N_ann   Kochhar  NKOCHHAR  515.123.4568    AD_VP  17000.0
2          102        Lex   De Haan   LDEHAAN  515.123.4569    AD_VP  17000.0
3          103  Alexander    Hunold   AHUNOLD  590.423.4567  IT_PROG   9000.0
4          104      Bruce     Ernst    BERNST  590.423.4568  IT_PROG   6000.0

   commission_pct  manager_id  department_id
0             NaN         NaN           90.0
1             NaN       100.0           90.0
2             NaN       100.0           90.0
3             NaN       102.0           60.0
4             NaN       103.0           60.0
6461.682242990654

In [2]:
# JSON 数据
df = pd.read_json('../data/data1.json')
print(type(df))
import json
with open('../data/test.json') as f:
    data = json.load(f)
print(type(data))
df = pd.DataFrame(data['users'])
df

<class 'pandas.core.frame.DataFrame'>
<class 'dict'>

   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20

### 02 缺失值处理

In [3]:
import pandas as pd
import numpy as np
s = pd.Series([15, 21, np.nan, None, pd.NA])
s

0      15
1      21
2     NaN
3    None
4    <NA>
dtype: object

In [4]:
print(s.isna())
print(s.isnull())

0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool

In [5]:
# 查看确实值个数
s.isna().sum()

np.int64(3)

In [6]:
df = pd.DataFrame([[1, pd.NA, 2], [2, 3, 5], [None, 4, 6]])
df.columns = ['第一列', '第二列', '第三列']
df

   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6

In [7]:
# 查看是否是缺失值
df.isna()

     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False

In [8]:
df.isnull()

     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False

In [9]:
 # 查看缺失值个数
df.isna().sum(axis=1)

0    1
1    0
2    1
dtype: int64

In [10]:
df.isna().sum()

第一列    1
第二列    1
第三列    0
dtype: int64

In [11]:
# 剔除缺失值
s.dropna()

0    15
1    21
dtype: object

In [12]:
df.dropna() # 含缺失值的记录被整条删除

   第一列 第二列  第三列
1  2.0   3    5

In [13]:
df.dropna(how='all') # 如果整行都是缺失值，就保留

   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6

In [14]:
df.dropna(thresh=2) # 如果至少有 n 个不是缺失值，就保留

   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6

In [15]:
df.dropna(axis=1) # 剔除一整列

   第三列
0    2
1    5
2    6

In [16]:
df.dropna(subset=['第一列']) # 剔除指定列中有缺失值的行

   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5

In [17]:
# 填充缺失值
df = pd.read_csv('../data/weather_withna.csv')
df.tail()

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN       NaN       NaN   NaN     NaN
1457  2015-12-28            NaN       NaN       NaN   NaN     NaN
1458  2015-12-29            NaN       NaN       NaN   NaN     NaN
1459  2015-12-30            NaN       NaN       NaN   NaN     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [18]:
df.isna().sum(axis=0)

date               0
precipitation    303
temp_max         303
temp_min         303
wind             303
weather          303
dtype: int64

In [19]:
df.head()

         date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

In [20]:
# 填充缺失值
df.fillna({'temp_max': 20}).tail() # 使用字典填充

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   NaN     NaN
1457  2015-12-28            NaN      20.0       NaN   NaN     NaN
1458  2015-12-29            NaN      20.0       NaN   NaN     NaN
1459  2015-12-30            NaN      20.0       NaN   NaN     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [21]:
df.fillna(df[['temp_max', 'temp_min', 'wind']].mean()) # 使用统计值填充

            date  precipitation   temp_max  temp_min      wind  weather
0     2012-01-01            0.0  12.800000  5.000000  4.700000  drizzle
1     2012-01-02           10.9  10.600000  2.800000  4.500000     rain
2     2012-01-03            0.8  11.700000  7.200000  2.300000     rain
3     2012-01-04           20.3  12.200000  5.600000  4.700000     rain
4     2012-01-05            1.3   8.900000  2.800000  6.100000     rain
...          ...            ...        ...       ...       ...      ...
1456  2015-12-27            NaN  15.851468  7.877202  3.242055      NaN
1457  2015-12-28            NaN  15.851468  7.877202  3.242055      NaN
1458  2015-12-29            NaN  15.851468  7.877202  3.242055      NaN
1459  2015-12-30            NaN  15.851468  7.877202  3.242055      NaN
1460  2015-12-31           20.6  12.200000  5.000000  3.800000     rain

[1461 rows x 6 columns]

In [22]:
df.ffill().tail() # 用前面的相邻值填充

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [23]:
df.bfill().tail() # 用后面的相邻值填充

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

### 03 重复数据处理

In [24]:
import pandas as pd

data = {
    'name': ['alice', 'alice', 'bob', 'alice', 'jack', 'bob'],
    'age': [26, 25, 30, 25, 35, 30],
    'city': ['NY', 'NY', 'LA', 'NY', 'SF', 'LA']
}
df = pd.DataFrame(data)

In [25]:
df

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [26]:
df.duplicated() # 整条记录都相同，标记为重复，True

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [27]:
df.drop_duplicates()

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
4   jack   35   SF

In [28]:
df.drop_duplicates(subset='name') # 根据指定列去重

    name  age city
0  alice   26   NY
2    bob   30   LA
4   jack   35   SF

In [29]:
df.drop_duplicates(subset='name', keep='last') # 根据指定列去重，保留最新出现的行

    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

### 04 数据类型转换

In [30]:
df = pd.read_csv('../data/sleep.csv')
df

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497,Sleep Apnea
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848,Insomnia
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255,Insomnia
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567,Sleep Apnea
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079,NaN

In [31]:
df.dtypes

person_id                    int64
gender                      object
age                          int64
occupation                  object
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                object
blood_pressure              object
heart_rate                   int64
daily_steps                  int64
sleep_disorder              object
dtype: object

In [32]:
df['age'] = df['age'].astype('int16')

In [33]:
df.dtypes

person_id                    int64
gender                      object
age                          int16
occupation                  object
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                object
blood_pressure              object
heart_rate                   int64
daily_steps                  int64
sleep_disorder              object
dtype: object

In [34]:
df.gender

0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: object

In [35]:
df['gender'] = df['gender'].astype('category') # 类别

In [36]:
df.dtypes

person_id                     int64
gender                     category
age                           int16
occupation                   object
sleep_duration              float64
sleep_quality               float64
physical_activity_level       int64
stress_level                  int64
bmi_category                 object
blood_pressure               object
heart_rate                    int64
daily_steps                   int64
sleep_disorder               object
dtype: object

In [37]:
df.gender

0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: category
Categories (2, object): ['Female', 'Male']

In [38]:
df['is_male'] = df['gender'].map({'Female': False, 'Male': True})

In [39]:
df.is_male

0       True
1      False
2       True
3       True
4       True
       ...
395    False
396    False
397    False
398    False
399     True
Name: is_male, Length: 400, dtype: category
Categories (2, bool): [False, True]

### 05 数据变形

In [40]:
import pandas as pd

In [41]:
data = {
    'ID': [1, 2],
    'name': ['alice', 'bob'],
    'math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89]
}

In [42]:
df = pd.DataFrame(data)

In [43]:
df

   ID   name  math  English  Science
0   1  alice    90       88       95
1   2    bob    85       92       89

In [44]:
df.T # 行列转置

             0    1
ID           1    2
name     alice  bob
math        90   85
English     88   92
Science     95   89

In [45]:
# 宽表转长表
df2 = pd.melt(df, id_vars=['ID', 'name'], var_name='科目', value_name='分数').sort_values('name')

In [46]:
df2

   ID   name       科目  分数
0   1  alice     math  90
2   1  alice  English  88
4   1  alice  Science  95
1   2    bob     math  85
3   2    bob  English  92
5   2    bob  Science  89

In [47]:
# 长表转宽表
df3 = pd.pivot(df2, index=['ID', 'name'], columns=['科目'], values=['分数'])

In [48]:
df3

              分数
科目       English Science math
ID name
1  alice      88      95   90
2  bob        92      89   85

In [49]:
data = {
    'ID': [1, 2],
    'name': ['alice smith', 'bob smith'],
    'math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89]
}

In [50]:
df = pd.DataFrame(data)

In [51]:
print(df)

   ID         name  math  English  Science
0   1  alice smith    90       88       95
1   2    bob smith    85       92       89

In [52]:
df['name'].str.split()

0    [alice, smith]
1      [bob, smith]
Name: name, dtype: object

In [53]:
print(df)

   ID         name  math  English  Science
0   1  alice smith    90       88       95
1   2    bob smith    85       92       89

In [54]:
# 分列
df[['fist_name', 'last_name']] = df['name'].str.split(' ', expand=True) # expand 把分割结果转为多列

In [55]:
print(df)

   ID         name  math  English  Science fist_name last_name
0   1  alice smith    90       88       95     alice     smith
1   2    bob smith    85       92       89       bob     smith

In [56]:
df = pd.read_csv('../data/sleep.csv')

In [57]:
print(df.head())

   person_id  gender  age     occupation  sleep_duration  sleep_quality  \
0          1    Male   29   Manual Labor             7.4            7.0
1          2  Female   43        Retired             4.2            4.9
2          3    Male   44        Retired             6.1            6.0
3          4    Male   29  Office Worker             8.3           10.0
4          5    Male   67        Retired             9.1            9.5

   physical_activity_level  stress_level bmi_category blood_pressure  \
0                       41             7        Obese         124/70
1                       41             5        Obese         131/86
2                      107             4  Underweight         122/70
3                       20            10        Obese         124/72
4                       19             4   Overweight         133/78

   heart_rate  daily_steps sleep_disorder
0          91         8539            NaN
1          81        18754            NaN
2          81         2857            NaN
3          55         6886            NaN
4          97        14945       Insomnia

In [58]:
print(df[['person_id', 'blood_pressure']])

     person_id blood_pressure
0            1         124/70
1            2         131/86
2            3         122/70
3            4         124/72
4            5         133/78
..         ...            ...
395        396         118/66
396        397         132/80
397        398         125/76
398        399         130/75
399        400         118/70

[400 rows x 2 columns]

In [59]:
df['blood_pressure'].str.split('/')

0      [124, 70]
1      [131, 86]
2      [122, 70]
3      [124, 72]
4      [133, 78]
         ...
395    [118, 66]
396    [132, 80]
397    [125, 76]
398    [130, 75]
399    [118, 70]
Name: blood_pressure, Length: 400, dtype: object

In [60]:
df[['high_pressure', 'low_pressure']] = df['blood_pressure'].str.split('/', expand=True)

In [61]:
df['high_pressure'] = df['high_pressure'].astype('int64')
df['low_pressure'] = df['low_pressure'].astype('int64')

In [62]:
print(df[['person_id', 'high_pressure', 'low_pressure', 'blood_pressure']].head())

   person_id  high_pressure  low_pressure blood_pressure
0          1            124            70         124/70
1          2            131            86         131/86
2          3            122            70         122/70
3          4            124            72         124/72
4          5            133            78         133/78

In [63]:
print(df.dtypes)

person_id                    int64
gender                      object
age                          int64
occupation                  object
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                object
blood_pressure              object
heart_rate                   int64
daily_steps                  int64
sleep_disorder              object
high_pressure                int64
low_pressure                 int64
dtype: object

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                400 non-null    int64
 1   gender                   400 non-null    object
 2   age                      400 non-null    int64
 3   occupation               400 non-null    object
 4   sleep_duration           400 non-null    float64
 5   sleep_quality            400 non-null    float64
 6   physical_activity_level  400 non-null    int64
 7   stress_level             400 non-null    int64
 8   bmi_category             400 non-null    object
 9   blood_pressure           400 non-null    object
 10  heart_rate               400 non-null    int64
 11  daily_steps              400 non-null    int64
 12  sleep_disorder           110 non-null    object
 13  high_pressure            400 non-null    int64
 14  low_pressure             400 non-null    int64
dtypes: float64(2), int64(8), object(5)
memory usage: 47.0+ KB

## 06 数据分箱

In [65]:
# 数据分箱 pd.cut(x, bins, labels)
import pandas as pd
df = pd.read_csv('../data/employees.csv')

In [66]:
df.head(10)

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,IT_PROG,4800.0,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,IT_PROG,4800.0,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,IT_PROG,4200.0,NaN,103.0,60.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,FI_MGR,12000.0,NaN,101.0,100.0
9,109,Daniel,Faviet,DFAVIET,515.124.4169,FI_ACCOUNT,9000.0,NaN,108.0,100.0

In [67]:
df1 = df[['employee_id', 'salary']].head(10) # 先取前10条调试

In [68]:
df1

   employee_id   salary
0          100  24000.0
1          101  17000.0
2          102  17000.0
3          103   9000.0
4          104   6000.0
5          105   4800.0
6          106   4800.0
7          107   4200.0
8          108  12000.0
9          109   9000.0

In [69]:
pd.cut(df1['salary'], bins=3) # bins=n, 分成n段区间，起始值和结束值是所有数据的最大值和最小值
# 4180 ~ 14100 ~ 24000

0    (17400.0, 24000.0]
1    (10800.0, 17400.0]
2    (10800.0, 17400.0]
3     (4180.2, 10800.0]
4     (4180.2, 10800.0]
5     (4180.2, 10800.0]
6     (4180.2, 10800.0]
7     (4180.2, 10800.0]
8    (10800.0, 17400.0]
9     (4180.2, 10800.0]
Name: salary, dtype: category
Categories (3, interval[float64, right]): [(4180.2, 10800.0] < (10800.0, 17400.0] < (17400.0, 24000.0]]

In [70]:
pd.cut(df1['salary'], bins=3).value_counts()

salary
(4180.2, 10800.0]     6
(10800.0, 17400.0]    3
(17400.0, 24000.0]    1
Name: count, dtype: int64

In [71]:
pd.cut(df1['salary'], bins=[0, 10000, 20000, 30000]) # bins为list时，分为指定的区间

0    (20000, 30000]
1    (10000, 20000]
2    (10000, 20000]
3        (0, 10000]
4        (0, 10000]
5        (0, 10000]
6        (0, 10000]
7        (0, 10000]
8    (10000, 20000]
9        (0, 10000]
Name: salary, dtype: category
Categories (3, interval[int64, right]): [(0, 10000] < (10000, 20000] < (20000, 30000]]

In [72]:
pd.cut(df1['salary'], bins=[0, 10000, 20000, 30000]).value_counts()

salary
(0, 10000]        6
(10000, 20000]    3
(20000, 30000]    1
Name: count, dtype: int64

In [73]:
pd.cut(df1['salary'], bins=[0, 10000, 20000, 30000], labels=['低', '中', '高']) # labels 指定每个区间的名称

0    高
1    中
2    中
3    低
4    低
5    低
6    低
7    低
8    中
9    低
Name: salary, dtype: category
Categories (3, object): ['低' < '中' < '高']

In [74]:
pd.cut(df1['salary'], bins=[0, 10000, 20000, 30000], labels=['低', '中', '高']).value_counts()

salary
低    6
中    3
高    1
Name: count, dtype: int64

In [75]:
df1['收入水平'] = pd.cut(df1['salary'], bins=[0, 10000, 20000, 30000], labels=['低', '中', '高'])

In [76]:
print(df1)

   employee_id   salary 收入水平
0          100  24000.0    高
1          101  17000.0    中
2          102  17000.0    中
3          103   9000.0    低
4          104   6000.0    低
5          105   4800.0    低
6          106   4800.0    低
7          107   4200.0    低
8          108  12000.0    中
9          109   9000.0    低

In [77]:
pd.qcut(df1['salary'], 3) # 按照频率分箱

0    (12000.0, 24000.0]
1    (12000.0, 24000.0]
2    (12000.0, 24000.0]
3     (6000.0, 12000.0]
4     (6000.0, 12000.0]
5    (4199.999, 6000.0]
6    (4199.999, 6000.0]
7    (4199.999, 6000.0]
8    (12000.0, 24000.0]
9     (6000.0, 12000.0]
Name: salary, dtype: category
Categories (3, interval[float64, right]): [(4199.999, 6000.0] < (6000.0, 12000.0] < (12000.0, 24000.0]]

In [79]:
pd.qcut(df1['salary'], 3).value_counts()

salary
(12000.0, 24000.0]    4
(4199.999, 6000.0]    3
(6000.0, 12000.0]     3
Name: count, dtype: int64

In [80]:
df = pd.read_csv('../data/sleep.csv')

In [81]:
df

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497,Sleep Apnea
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848,Insomnia
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255,Insomnia
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567,Sleep Apnea
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079,NaN

In [89]:
df1 = df[['person_id', 'sleep_quality']].head(10)

In [92]:
pd.cut(df1['sleep_quality'], bins=3, labels=['差', '中', '优'])

0    中
1    差
2    差
3    优
4    优
5    中
6    中
7    中
8    中
9    差
Name: sleep_quality, dtype: category
Categories (3, object): ['差' < '中' < '优']

In [93]:
df1['睡眠质量'] = pd.cut(df1['sleep_quality'], bins=3, labels=['差', '中', '优'])

In [94]:
df1

   person_id  sleep_quality 睡眠质量
0          1            7.0    中
1          2            4.9    差
2          3            6.0    差
3          4           10.0    优
4          5            9.5    优
5          6            6.9    中
6          7            6.1    中
7          8            6.2    中
8          9            7.2    中
9         10            4.0    差

In [95]:
df1['睡眠质量'].value_counts()

睡眠质量
中    5
差    3
优    2
Name: count, dtype: int64

In [96]:
df['gender'] = df['gender'].astype('category') # 类别

In [97]:
df['gender'].value_counts()

gender
Female    201
Male      199
Name: count, dtype: int64

In [98]:
# 字符串 -> 类别 -> 统计
# 数值 -> 分箱 -> 统计

In [101]:
df[['gender']].dtypes

gender    category
dtype: object

In [102]:
df1[['睡眠质量']].dtypes

睡眠质量    category
dtype: object

- df.rename() 给列/索引重命名
- df.set_index() 设置索引
- df.reset_index()

In [110]:
df = pd.DataFrame({
    'name': ['jack', 'alice', 'tom', 'bob'],
    'age': [20, 30, 40, 50],
    'gender': ['female', 'male', 'female', 'male']
})

In [111]:
df

    name  age  gender
0   jack   20  female
1  alice   30    male
2    tom   40  female
3    bob   50    male

In [112]:
df.set_index('name', inplace=True) # inplace 对当前df直接进行对应修改

In [113]:
df

       age  gender
name
jack    20  female
alice   30    male
tom     40  female
bob     50    male

In [114]:
df.reset_index(inplace=True)

In [115]:
df

    name  age  gender
0   jack   20  female
1  alice   30    male
2    tom   40  female
3    bob   50    male

In [121]:
df.rename(columns={'age': '年龄'}, index={0: 4}, inplace=True)

In [122]:
df

    name  年龄  gender
4   jack  20  female
1  alice  30    male
2    tom  40  female
3    bob  50    male

In [123]:
df.index

Index([4, 1, 2, 3], dtype='int64')

In [124]:
df.index = [1, 2, 3, 4]

In [125]:
df.index

Index([1, 2, 3, 4], dtype='int64')

In [126]:
df.columns

Index(['name', '年龄', 'gender'], dtype='object')

In [127]:
df.columns = ['姓名', '年龄', '性别']

In [129]:
df.columns

Index(['姓名', '年龄', '性别'], dtype='object')

In [130]:
df

      姓名  年龄      性别
1   jack  20  female
2  alice  30    male
3    tom  40  female
4    bob  50    male