# Data analysis learning
## 02 data precessing
### 01 时间数据处理

In [17]:
import pandas as pd
# 时间数据处理
d = pd.Timestamp('2026-8-13 12:17') # 时间戳

In [18]:
d

Timestamp('2026-08-13 12:17:00')

In [4]:
type(d)

pandas._libs.tslibs.timestamps.Timestamp

In [13]:
# 时间戳可以取出的属性
print('年', d.year)
print('月', d.month)
print('日', d.day)
print('时', d.hour)
print('分', d.minute)
print('秒', d.second)
print('季度', d.quarter)

年 2026
月 8
日 13
时 12
分 17
秒 0
季度 3

In [14]:
# 判断相关
print('是否是月底', d.is_month_end)

是否是月底 False

In [24]:
# 常用方法
print('星期', d.day_name()) # 星期几
print('转换为天维度', d.to_period('D')) # period 周期
print('转换为季度', d.to_period('Q'))
print('转换为年度', d.to_period('Y'))
print('转换为月度', d.to_period('M'))
print('转换为周维度', d.to_period('W'))

星期 Thursday
转换为天维度 2026-08-13
转换为季度 2026Q3
转换为年度 2026
转换为月度 2026-08
转换为周维度 2026-08-10/2026-08-16

In [28]:
# 字符串转为日期类型
d = pd.to_datetime('2026/08/13 12:37:15')

In [29]:
d

Timestamp('2026-08-13 12:37:15')

In [30]:
type(d)

pandas._libs.tslibs.timestamps.Timestamp

In [42]:
# DataFrame 中的日期转换

df = pd.DataFrame({
    'sales': [100, 200, 300],
    'date': ['20260810', '20260811', '20260812']
})

In [43]:
df

   sales      date
0    100  20260810
1    200  20260811
2    300  20260812

In [44]:
df['datetime'] = pd.to_datetime(df['date'])

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sales     3 non-null      int64
 1   date      3 non-null      object
 2   datetime  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 200.0+ bytes

In [46]:
df['week'] = df['datetime'].dt.day_name() # DateFrame中使用datetime的属性和方法，加一个.dt

In [48]:
df

   sales      date   datetime       week
0    100  20260810 2026-08-10     Monday
1    200  20260811 2026-08-11    Tuesday
2    300  20260812 2026-08-12  Wednesday

In [50]:
df['datetime'].dt.year

0    2026
1    2026
2    2026
Name: datetime, dtype: int32