# data analysis learning
## 01 数据导入和导出

In [1]:
# 数据导入
import pandas as pd
from pandas.core.dtypes import dtypes

df = pd.read_csv('D:/Code/Python-Data-Analysis-Learning/data/employees.csv')
print(type(df))
print(df.head())
print(df.salary.mean())
# 数据导出
df = df.tail()
df.to_csv('D:/Code/Python-Data-Analysis-Learning/data/new.csv')

<class 'pandas.core.frame.DataFrame'>
   employee_id first_name last_name     email  phone_number   job_id   salary  \
0          100     Steven      King     SKING  515.123.4567  AD_PRES  24000.0
1          101      N_ann   Kochhar  NKOCHHAR  515.123.4568    AD_VP  17000.0
2          102        Lex   De Haan   LDEHAAN  515.123.4569    AD_VP  17000.0
3          103  Alexander    Hunold   AHUNOLD  590.423.4567  IT_PROG   9000.0
4          104      Bruce     Ernst    BERNST  590.423.4568  IT_PROG   6000.0

   commission_pct  manager_id  department_id
0             NaN         NaN           90.0
1             NaN       100.0           90.0
2             NaN       100.0           90.0
3             NaN       102.0           60.0
4             NaN       103.0           60.0
6461.682242990654

In [2]:
# JSON 数据
df = pd.read_json('D:/Code/Python-Data-Analysis-Learning/data/data1.json')
print(type(df))
import json
with open('D:/Code/Python-Data-Analysis-Learning/data/test.json') as f:
    data = json.load(f)
print(type(data))
df = pd.DataFrame(data['users'])
df

<class 'pandas.core.frame.DataFrame'>
<class 'dict'>

   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20

## 02 缺失值处理

In [3]:
import pandas as pd
import numpy as np
s = pd.Series([15, 21, np.nan, None, pd.NA])
s

0      15
1      21
2     NaN
3    None
4    <NA>
dtype: object

In [4]:
print(s.isna())
print(s.isnull())

0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool

In [5]:
# 查看确实值个数
s.isna().sum()

np.int64(3)

In [6]:
df = pd.DataFrame([[1, pd.NA, 2], [2, 3, 5], [None, 4, 6]])
df.columns = ['第一列', '第二列', '第三列']
df

   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6

In [7]:
# 查看是否是缺失值
df.isna()

     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False

In [8]:
df.isnull()

     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False

In [9]:
 # 查看缺失值个数
df.isna().sum(axis=1)

0    1
1    0
2    1
dtype: int64

In [10]:
df.isna().sum()

第一列    1
第二列    1
第三列    0
dtype: int64

In [11]:
# 剔除缺失值
s.dropna()

0    15
1    21
dtype: object

In [12]:
df.dropna() # 含缺失值的记录被整条删除

   第一列 第二列  第三列
1  2.0   3    5

In [13]:
df.dropna(how='all') # 如果整行都是缺失值，就保留

   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6

In [14]:
df.dropna(thresh=2) # 如果至少有 n 个不是缺失值，就保留

   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6

In [15]:
df.dropna(axis=1) # 剔除一整列

   第三列
0    2
1    5
2    6

In [16]:
df.dropna(subset=['第一列']) # 剔除指定列中有缺失值的行

   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5

In [17]:
# 填充缺失值
df = pd.read_csv('D:/Code/Python-Data-Analysis-Learning/data/weather_withna.csv')
df.tail()

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN       NaN       NaN   NaN     NaN
1457  2015-12-28            NaN       NaN       NaN   NaN     NaN
1458  2015-12-29            NaN       NaN       NaN   NaN     NaN
1459  2015-12-30            NaN       NaN       NaN   NaN     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [18]:
df.isna().sum(axis=0)

date               0
precipitation    303
temp_max         303
temp_min         303
wind             303
weather          303
dtype: int64

In [19]:
df.head()

         date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

In [28]:
# 填充缺失值
df.fillna({'temp_max': 20}).tail() # 使用字典填充

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   NaN     NaN
1457  2015-12-28            NaN      20.0       NaN   NaN     NaN
1458  2015-12-29            NaN      20.0       NaN   NaN     NaN
1459  2015-12-30            NaN      20.0       NaN   NaN     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [30]:
df.fillna(df[['temp_max', 'temp_min', 'wind']].mean()) # 使用统计值填充

            date  precipitation   temp_max  temp_min      wind  weather
0     2012-01-01            0.0  12.800000  5.000000  4.700000  drizzle
1     2012-01-02           10.9  10.600000  2.800000  4.500000     rain
2     2012-01-03            0.8  11.700000  7.200000  2.300000     rain
3     2012-01-04           20.3  12.200000  5.600000  4.700000     rain
4     2012-01-05            1.3   8.900000  2.800000  6.100000     rain
...          ...            ...        ...       ...       ...      ...
1456  2015-12-27            NaN  15.851468  7.877202  3.242055      NaN
1457  2015-12-28            NaN  15.851468  7.877202  3.242055      NaN
1458  2015-12-29            NaN  15.851468  7.877202  3.242055      NaN
1459  2015-12-30            NaN  15.851468  7.877202  3.242055      NaN
1460  2015-12-31           20.6  12.200000  5.000000  3.800000     rain

[1461 rows x 6 columns]

In [26]:
df.ffill().tail() # 用前面的相邻值填充

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [27]:
df.bfill().tail() # 用后面的相邻值填充

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

## 03 重复数据处理

In [33]:
import pandas as pd
import numpy as np

data = {
    'name': ['alice', 'alice', 'bob', 'alice', 'jack', 'bob'],
    'age': [26, 25, 30, 25, 35, 30],
    'city': ['NY', 'NY', 'LA', 'NY', 'SF', 'LA']
}
df = pd.DataFrame(data)

In [34]:
df

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [35]:
df.duplicated() # 整条记录都相同，标记为重复，True

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [36]:
df.drop_duplicates()

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
4   jack   35   SF

In [37]:
df.drop_duplicates(subset='name') # 根据指定列去重

    name  age city
0  alice   26   NY
2    bob   30   LA
4   jack   35   SF

In [39]:
df.drop_duplicates(subset='name', keep='last') # 根据指定列去重，保留最新出现的行

    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA