# Data analysis learning
## 02 data precessing
### 01 时间数据处理

In [1]:
import pandas as pd
# 时间数据处理
d = pd.Timestamp('2026-8-13 12:17') # 时间戳

In [2]:
d

Timestamp('2026-08-13 12:17:00')

In [3]:
type(d)

pandas._libs.tslibs.timestamps.Timestamp

In [4]:
# 时间戳可以取出的属性
print('年', d.year)
print('月', d.month)
print('日', d.day)
print('时', d.hour)
print('分', d.minute)
print('秒', d.second)
print('季度', d.quarter)

年 2026
月 8
日 13
时 12
分 17
秒 0
季度 3

In [5]:
# 判断相关
print('是否是月底', d.is_month_end)

是否是月底 False

In [6]:
# 常用方法
print('星期', d.day_name()) # 星期几
print('转换为天维度', d.to_period('D')) # period 周期
print('转换为季度', d.to_period('Q'))
print('转换为年度', d.to_period('Y'))
print('转换为月度', d.to_period('M'))
print('转换为周维度', d.to_period('W'))

星期 Thursday
转换为天维度 2026-08-13
转换为季度 2026Q3
转换为年度 2026
转换为月度 2026-08
转换为周维度 2026-08-10/2026-08-16

In [7]:
# 字符串转为日期类型
d = pd.to_datetime('2026/08/13 12:37:15')

In [8]:
d

Timestamp('2026-08-13 12:37:15')

In [9]:
type(d)

pandas._libs.tslibs.timestamps.Timestamp

In [10]:
# DataFrame 中的日期转换

df = pd.DataFrame({
    'sales': [100, 200, 300],
    'date': ['20260810', '20260811', '20260812']
})

In [11]:
df

   sales      date
0    100  20260810
1    200  20260811
2    300  20260812

In [12]:
df['datetime'] = pd.to_datetime(df['date'])

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sales     3 non-null      int64
 1   date      3 non-null      object
 2   datetime  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 200.0+ bytes

In [14]:
df['week'] = df['datetime'].dt.day_name() # DateFrame中使用datetime的属性和方法，加一个.dt

In [15]:
df

   sales      date   datetime       week
0    100  20260810 2026-08-10     Monday
1    200  20260811 2026-08-11    Tuesday
2    300  20260812 2026-08-12  Wednesday

In [16]:
df['datetime'].dt.year

0    2026
1    2026
2    2026
Name: datetime, dtype: int32

In [17]:
# csv 中的日期转换

df = pd.read_csv('../data/weather.csv')

In [18]:
df

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [19]:
df.dtypes

date              object
precipitation    float64
temp_max         float64
temp_min         float64
wind             float64
weather           object
dtype: object

In [20]:
df['datetime'] = pd.to_datetime(df['date'])

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   object
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object
 6   datetime       1461 non-null   datetime64[ns]
 7   week           1461 non-null   object
dtypes: datetime64[ns](1), float64(4), object(3)
memory usage: 91.4+ KB

In [25]:
df['week'] = df['datetime'].dt.day_name()

In [26]:
df

,date,precipitation,temp_max,temp_min,wind,weather,datetime,week
0,2012-01-01,0.0,12.8,5.0,4.7,drizzle,2012-01-01,Sunday
1,2012-01-02,10.9,10.6,2.8,4.5,rain,2012-01-02,Monday
2,2012-01-03,0.8,11.7,7.2,2.3,rain,2012-01-03,Tuesday
3,2012-01-04,20.3,12.2,5.6,4.7,rain,2012-01-04,Wednesday
4,2012-01-05,1.3,8.9,2.8,6.1,rain,2012-01-05,Thursday
...,...,...,...,...,...,...,...,...
1456,2015-12-27,8.6,4.4,1.7,2.9,rain,2015-12-27,Sunday
1457,2015-12-28,1.5,5.0,1.7,1.3,rain,2015-12-28,Monday
1458,2015-12-29,0.0,7.2,0.6,2.6,fog,2015-12-29,Tuesday
1459,2015-12-30,0.0,5.6,-1.0,3.4,sun,2015-12-30,Wednesday
1460,2015-12-31,0.0,5.6,-2.1,3.5,sun,2015-12-31,Thursday

In [27]:
# 导入csv 时就对日期进行解析

df = pd.read_csv('../data/weather.csv', parse_dates=['date'])

In [28]:
df

           date  precipitation  temp_max  temp_min  wind  weather
0    2012-01-01            0.0      12.8       5.0   4.7  drizzle
1    2012-01-02           10.9      10.6       2.8   4.5     rain
2    2012-01-03            0.8      11.7       7.2   2.3     rain
3    2012-01-04           20.3      12.2       5.6   4.7     rain
4    2012-01-05            1.3       8.9       2.8   6.1     rain
...         ...            ...       ...       ...   ...      ...
1456 2015-12-27            8.6       4.4       1.7   2.9     rain
1457 2015-12-28            1.5       5.0       1.7   1.3     rain
1458 2015-12-29            0.0       7.2       0.6   2.6      fog
1459 2015-12-30            0.0       5.6      -1.0   3.4      sun
1460 2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[ns]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 68.6+ KB

In [30]:
df['date'].dt.day_name()

0          Sunday
1          Monday
2         Tuesday
3       Wednesday
4        Thursday
          ...
1456       Sunday
1457       Monday
1458      Tuesday
1459    Wednesday
1460     Thursday
Name: date, Length: 1461, dtype: object

In [32]:
# 日期数据作为索引
df.set_index('date', inplace=True) # 把'date'设置为原df的索引

In [33]:
df

            precipitation  temp_max  temp_min  wind  weather
date
2012-01-01            0.0      12.8       5.0   4.7  drizzle
2012-01-02           10.9      10.6       2.8   4.5     rain
2012-01-03            0.8      11.7       7.2   2.3     rain
2012-01-04           20.3      12.2       5.6   4.7     rain
2012-01-05            1.3       8.9       2.8   6.1     rain
...                   ...       ...       ...   ...      ...
2015-12-27            8.6       4.4       1.7   2.9     rain
2015-12-28            1.5       5.0       1.7   1.3     rain
2015-12-29            0.0       7.2       0.6   2.6      fog
2015-12-30            0.0       5.6      -1.0   3.4      sun
2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 5 columns]

In [35]:
df.loc['2013-01':'2013-02'] # 日期设为索引后，使用索引切片就可以取出某个时间段的数据

            precipitation  temp_max  temp_min  wind  weather
date
2013-01-01            0.0       5.0      -2.8   2.7      sun
2013-01-02            0.0       6.1      -1.1   3.2      sun
2013-01-03            4.1       6.7      -1.7   3.0     rain
2013-01-04            2.5      10.0       2.2   2.8     rain
2013-01-05            3.0       6.7       4.4   3.1     rain
2013-01-06            2.0       7.2       2.8   3.0     rain
2013-01-07            2.3      10.0       4.4   7.3     rain
2013-01-08           16.3      11.7       5.6   6.3     rain
2013-01-09           38.4      10.0       1.7   5.1     rain
2013-01-10            0.3       3.3      -0.6   2.1     snow
2013-01-11            0.0       2.8      -2.8   1.9  drizzle
2013-01-12            0.0       2.8      -3.9   2.0      sun
2013-01-13            0.0       2.2      -4.4   1.5      sun
2013-01-14            0.0       3.3      -2.2   1.3      sun
2013-01-15            0.0       6.7      -0.6   2.3      sun
2013-01-16            0.0       6.1      -3.9   1.8  drizzle
2013-01-17            0.0       3.9      -2.8   1.0  drizzle
2013-01-18            0.0       3.3      -1.1   1.3  drizzle
2013-01-19            0.0       1.1      -0.6   1.9  drizzle
2013-01-20            0.0       3.3      -0.6   2.1  drizzle
2013-01-21            0.0       2.2      -1.7   1.1  drizzle
2013-01-22            0.0       3.3      -1.7   0.6  drizzle
2013-01-23            5.1       7.2       2.2   3.1     rain
2013-01-24            5.8       7.2       1.1   2.6     rain
2013-01-25            3.0      10.6       2.8   2.1     rain
2013-01-26            2.3       8.3       3.9   4.5     rain
2013-01-27            1.8       5.6       3.9   4.5     rain
2013-01-28            7.9       6.1       3.3   3.2     rain
2013-01-29            4.3       8.3       5.0   3.9     rain
2013-01-30            3.6       8.9       6.7   3.9     rain
2013-01-31            3.0       9.4       7.2   4.0     rain
2013-02-01            0.3      11.7       5.0   2.9     rain
2013-02-02            0.0       6.1       2.8   2.0  drizzle
2013-02-03            2.3       8.9       2.8   2.9     rain
2013-02-04            0.0      10.6       6.7   2.6     rain
2013-02-05            3.3      10.0       6.7   5.1     rain
2013-02-06            1.0      10.6       6.1   4.5     rain
2013-02-07            1.3       9.4       3.3   4.1     rain
2013-02-08            0.0       7.8       2.2   1.3      sun
2013-02-09            0.3       8.3       4.4   1.3     rain
2013-02-10            0.0       8.9       1.7   2.0  drizzle
2013-02-11            0.3       8.3       4.4   1.4     rain
2013-02-12            1.0      11.1       7.2   5.6     rain
2013-02-13            2.3       9.4       7.2   4.1     rain
2013-02-14            1.0       9.4       5.6   2.2     rain
2013-02-15            0.0      13.3       5.0   2.4  drizzle
2013-02-16            0.0      11.1       3.9   5.6     rain
2013-02-17            0.0       9.4       4.4   3.4     rain
2013-02-18            0.0       7.8       3.9   1.9     rain
2013-02-19            0.0      10.6       1.7   3.4      sun
2013-02-20            1.5       7.8       1.1   2.1     rain
2013-02-21            0.5       6.7       3.9   6.2     rain
2013-02-22            9.4       7.8       3.9   8.1     rain
2013-02-23            0.3      10.0       3.9   4.6     rain
2013-02-24            0.0       8.9       5.0   5.5     rain
2013-02-25            2.3      10.6       3.3   7.1     rain
2013-02-26            0.5       8.9       3.9   3.8     rain
2013-02-27            4.6      10.0       4.4   1.8     rain
2013-02-28            8.1      11.7       6.7   3.8     rain

- 时间间隔

In [37]:
dt1 = pd.Timestamp('2013-01-15')
dt2 = pd.Timestamp('2013-02-23')
dt3 = dt2 - dt1

In [39]:
print(type(dt3))
print(dt3)

<class 'pandas._libs.tslibs.timedeltas.Timedelta'>
39 days 00:00:00

In [44]:
df = pd.read_csv('../data/weather.csv', parse_dates=['date'])

In [45]:
df

           date  precipitation  temp_max  temp_min  wind  weather
0    2012-01-01            0.0      12.8       5.0   4.7  drizzle
1    2012-01-02           10.9      10.6       2.8   4.5     rain
2    2012-01-03            0.8      11.7       7.2   2.3     rain
3    2012-01-04           20.3      12.2       5.6   4.7     rain
4    2012-01-05            1.3       8.9       2.8   6.1     rain
...         ...            ...       ...       ...   ...      ...
1456 2015-12-27            8.6       4.4       1.7   2.9     rain
1457 2015-12-28            1.5       5.0       1.7   1.3     rain
1458 2015-12-29            0.0       7.2       0.6   2.6      fog
1459 2015-12-30            0.0       5.6      -1.0   3.4      sun
1460 2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[ns]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 68.6+ KB

In [47]:
df['delta'] = df['date'] - df['date'][0]

In [48]:
df

           date  precipitation  temp_max  temp_min  wind  weather     delta
0    2012-01-01            0.0      12.8       5.0   4.7  drizzle    0 days
1    2012-01-02           10.9      10.6       2.8   4.5     rain    1 days
2    2012-01-03            0.8      11.7       7.2   2.3     rain    2 days
3    2012-01-04           20.3      12.2       5.6   4.7     rain    3 days
4    2012-01-05            1.3       8.9       2.8   6.1     rain    4 days
...         ...            ...       ...       ...   ...      ...       ...
1456 2015-12-27            8.6       4.4       1.7   2.9     rain 1456 days
1457 2015-12-28            1.5       5.0       1.7   1.3     rain 1457 days
1458 2015-12-29            0.0       7.2       0.6   2.6      fog 1458 days
1459 2015-12-30            0.0       5.6      -1.0   3.4      sun 1459 days
1460 2015-12-31            0.0       5.6      -2.1   3.5      sun 1460 days

[1461 rows x 7 columns]

In [49]:
df.set_index('delta', inplace=True)

In [50]:
df

                date  precipitation  temp_max  temp_min  wind  weather
delta
0 days    2012-01-01            0.0      12.8       5.0   4.7  drizzle
1 days    2012-01-02           10.9      10.6       2.8   4.5     rain
2 days    2012-01-03            0.8      11.7       7.2   2.3     rain
3 days    2012-01-04           20.3      12.2       5.6   4.7     rain
4 days    2012-01-05            1.3       8.9       2.8   6.1     rain
...              ...            ...       ...       ...   ...      ...
1456 days 2015-12-27            8.6       4.4       1.7   2.9     rain
1457 days 2015-12-28            1.5       5.0       1.7   1.3     rain
1458 days 2015-12-29            0.0       7.2       0.6   2.6      fog
1459 days 2015-12-30            0.0       5.6      -1.0   3.4      sun
1460 days 2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [51]:
df.loc['0 days':'100 days']

               date  precipitation  temp_max  temp_min  wind  weather
delta
0 days   2012-01-01            0.0      12.8       5.0   4.7  drizzle
1 days   2012-01-02           10.9      10.6       2.8   4.5     rain
2 days   2012-01-03            0.8      11.7       7.2   2.3     rain
3 days   2012-01-04           20.3      12.2       5.6   4.7     rain
4 days   2012-01-05            1.3       8.9       2.8   6.1     rain
...             ...            ...       ...       ...   ...      ...
96 days  2012-04-06            0.3      11.1       3.3   2.6     rain
97 days  2012-04-07            0.0      16.1       1.7   4.3      sun
98 days  2012-04-08            0.0      21.1       7.2   4.1      sun
99 days  2012-04-09            0.0      20.0       6.1   2.1      sun
100 days 2012-04-10            0.0      17.8       8.9   3.2     rain

[101 rows x 6 columns]

- 时间序列

In [55]:
days = pd.date_range('2025-07-03', '2026-02-03', freq='W')

In [56]:
days

DatetimeIndex(['2025-07-06', '2025-07-13', '2025-07-20', '2025-07-27',
               '2025-08-03', '2025-08-10', '2025-08-17', '2025-08-24',
               '2025-08-31', '2025-09-07', '2025-09-14', '2025-09-21',
               '2025-09-28', '2025-10-05', '2025-10-12', '2025-10-19',
               '2025-10-26', '2025-11-02', '2025-11-09', '2025-11-16',
               '2025-11-23', '2025-11-30', '2025-12-07', '2025-12-14',
               '2025-12-21', '2025-12-28', '2026-01-04', '2026-01-11',
               '2026-01-18', '2026-01-25', '2026-02-01'],
              dtype='datetime64[ns]', freq='W-SUN')

In [57]:
days = pd.date_range('2025-07-03', periods=10, freq='W')

In [58]:
days

DatetimeIndex(['2025-07-06', '2025-07-13', '2025-07-20', '2025-07-27',
               '2025-08-03', '2025-08-10', '2025-08-17', '2025-08-24',
               '2025-08-31', '2025-09-07'],
              dtype='datetime64[ns]', freq='W-SUN')

In [59]:
days = pd.date_range('2025-07-03', periods=10, freq='YE')

In [60]:
days

DatetimeIndex(['2025-12-31', '2026-12-31', '2027-12-31', '2028-12-31',
               '2029-12-31', '2030-12-31', '2031-12-31', '2032-12-31',
               '2033-12-31', '2034-12-31'],
              dtype='datetime64[ns]', freq='YE-DEC')

In [61]:
days = pd.date_range('2025-07-03', periods=10, freq='YS')

In [62]:
days

DatetimeIndex(['2026-01-01', '2027-01-01', '2028-01-01', '2029-01-01',
               '2030-01-01', '2031-01-01', '2032-01-01', '2033-01-01',
               '2034-01-01', '2035-01-01'],
              dtype='datetime64[ns]', freq='YS-JAN')

In [65]:
df = pd.read_csv('../data/weather.csv', parse_dates=['date'])

In [66]:
df

           date  precipitation  temp_max  temp_min  wind  weather
0    2012-01-01            0.0      12.8       5.0   4.7  drizzle
1    2012-01-02           10.9      10.6       2.8   4.5     rain
2    2012-01-03            0.8      11.7       7.2   2.3     rain
3    2012-01-04           20.3      12.2       5.6   4.7     rain
4    2012-01-05            1.3       8.9       2.8   6.1     rain
...         ...            ...       ...       ...   ...      ...
1456 2015-12-27            8.6       4.4       1.7   2.9     rain
1457 2015-12-28            1.5       5.0       1.7   1.3     rain
1458 2015-12-29            0.0       7.2       0.6   2.6      fog
1459 2015-12-30            0.0       5.6      -1.0   3.4      sun
1460 2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [71]:
df.set_index('date', inplace=True)

In [72]:
# 重新采样

In [76]:
df[['temp_max', 'temp_min']].resample('YS').mean()

             temp_max  temp_min
date
2012-01-01  15.276776  7.289617
2013-01-01  16.058904  8.153973
2014-01-01  16.995890  8.662466
2015-01-01  17.427945  8.835616

In [77]:
df[['temp_max', 'temp_min']].resample('YE').mean()

             temp_max  temp_min
date
2012-12-31  15.276776  7.289617
2013-12-31  16.058904  8.153973
2014-12-31  16.995890  8.662466
2015-12-31  17.427945  8.835616

### 02 分组聚合

In [78]:
# df.groupby('分组的字段')['聚合的字段'].聚合函数()

In [79]:
import pandas as pd

In [80]:
df = pd.read_csv('../data/employees.csv')

In [81]:
df

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,MK_REP,6000.0,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,HR_REP,6500.0,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,PR_REP,10000.0,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,AC_MGR,12000.0,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,AC_ACCOUNT,8300.0,NaN,205.0,110.0

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   employee_id     107 non-null    int64
 1   first_name      107 non-null    object
 2   last_name       107 non-null    object
 3   email           107 non-null    object
 4   phone_number    107 non-null    object
 5   job_id          107 non-null    object
 6   salary          107 non-null    float64
 7   commission_pct  35 non-null     float64
 8   manager_id      106 non-null    float64
 9   department_id   106 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 8.5+ KB

In [91]:
df['department_id'].isna().sum()

np.int64(1)

In [93]:
df.dropna(subset=['department_id'], inplace=True)
df['department_id'].isna().sum()

np.int64(0)

In [94]:
df['department_id'] = df['department_id'].astype('int')

In [95]:
# 计算不同部门的平均薪资

In [98]:
df.groupby('department_id')

In [100]:
df.groupby('department_id').groups # 查看所有的分组

{10: [100], 20: [101, 102], 30: [14, 15, 16, 17, 18, 19], 40: [103], 50: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 60: [3, 4, 5, 6, 7], 70: [104], 80: [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 79], 90: [0, 1, 2], 100: [8, 9, 10, 11, 12, 13], 110: [105, 106]}

In [103]:
df.groupby('department_id').get_group(30) # 查看具体的某个分组数据

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
14,114,Den,Raphaely,DRAPHEAL,515.127.4561,PU_MAN,11000.0,NaN,100.0,30
15,115,Alexander,Khoo,AKHOO,515.127.4562,PU_CLERK,3100.0,NaN,114.0,30
16,116,Shelli,Baida,SBAIDA,515.127.4563,PU_CLERK,2900.0,NaN,114.0,30
17,117,Sigal,Tobias,STOBIAS,515.127.4564,PU_CLERK,2800.0,NaN,114.0,30
18,118,Guy,Himuro,GHIMURO,515.127.4565,PU_CLERK,2600.0,NaN,114.0,30
19,119,Karen,Colmenares,KCOLMENA,515.127.4566,PU_CLERK,2500.0,NaN,114.0,30

In [105]:
df.groupby('department_id')[['salary']]

In [106]:
df.groupby('department_id')[['salary']].mean()

                     salary
department_id
10              4400.000000
20              9500.000000
30              4150.000000
40              6500.000000
50              3475.555556
60              5760.000000
70             10000.000000
80              8955.882353
90             19333.333333
100             8600.000000
110            10150.000000

In [109]:
df2 = df.groupby('department_id')[['salary']].mean()

In [111]:
df2['salary'] = df2['salary'].round(2)

In [112]:
df2

                 salary
department_id
10              4400.00
20              9500.00
30              4150.00
40              6500.00
50              3475.56
60              5760.00
70             10000.00
80              8955.88
90             19333.33
100             8600.00
110            10150.00

In [113]:
df2 = df2.reset_index()

In [114]:
df2

    department_id    salary
0              10   4400.00
1              20   9500.00
2              30   4150.00
3              40   6500.00
4              50   3475.56
5              60   5760.00
6              70  10000.00
7              80   8955.88
8              90  19333.33
9             100   8600.00
10            110  10150.00

In [115]:
df2.sort_values('salary', ascending=False)

    department_id    salary
8              90  19333.33
10            110  10150.00
6              70  10000.00
1              20   9500.00
7              80   8955.88
9             100   8600.00
3              40   6500.00
5              60   5760.00
0              10   4400.00
2              30   4150.00
4              50   3475.56

In [116]:
# 计算不同部门不同岗位的平均薪资情况

In [117]:
df.groupby(['department_id', 'job_id'])

In [118]:
df.groupby(['department_id', 'job_id']).groups

{(10, 'AD_ASST'): [100], (20, 'MK_MAN'): [101], (20, 'MK_REP'): [102], (30, 'PU_CLERK'): [15, 16, 17, 18, 19], (30, 'PU_MAN'): [14], (40, 'HR_REP'): [103], (50, 'SH_CLERK'): [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], (50, 'ST_CLERK'): [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44], (50, 'ST_MAN'): [20, 21, 22, 23, 24], (60, 'IT_PROG'): [3, 4, 5, 6, 7], (70, 'PR_REP'): [104], (80, 'SA_MAN'): [45, 46, 47, 48, 49], (80, 'SA_REP'): [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 79], (90, 'AD_PRES'): [0], (90, 'AD_VP'): [1, 2], (100, 'FI_ACCOUNT'): [9, 10, 11, 12, 13], (100, 'FI_MGR'): [8], (110, 'AC_ACCOUNT'): [106], (110, 'AC_MGR'): [105]}

In [135]:
df_new = df.groupby(['department_id', 'job_id'])[['salary']].mean()[['salary']].round(1)

In [136]:
df_new.reset_index(inplace=True)

In [137]:
df_new.sort_values('salary', ascending=False)

    department_id      job_id   salary
13             90     AD_PRES  24000.0
14             90       AD_VP  17000.0
1              20      MK_MAN  13000.0
11             80      SA_MAN  12200.0
16            100      FI_MGR  12000.0
18            110      AC_MGR  12000.0
4              30      PU_MAN  11000.0
10             70      PR_REP  10000.0
12             80      SA_REP   8396.6
17            110  AC_ACCOUNT   8300.0
15            100  FI_ACCOUNT   7920.0
8              50      ST_MAN   7280.0
5              40      HR_REP   6500.0
2              20      MK_REP   6000.0
9              60     IT_PROG   5760.0
0              10     AD_ASST   4400.0
6              50    SH_CLERK   3215.0
7              50    ST_CLERK   2785.0
3              30    PU_CLERK   2780.0