# pandas 综合案例

## 01 企鹅数据分析

In [1]:
# 一般步骤：
    # 1. 导入一些必要的库
    # 2. 导入数据
    # 3. 数据清洗
    # 4. 数据特征的构造
    # 5. 数据分析

In [2]:
# 1. 导入一些必要的库
import pandas as pd

In [3]:
# 2. 导入数据
df = pd.read_csv('../data/penguins.csv')

In [4]:
df.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [6]:
# 3. 数据清洗
df.isna().sum(axis=0)

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
df.isna().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 333 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            333 non-null    object
 1   island             333 non-null    object
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    float64
 5   body_mass_g        333 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 20.8+ KB

In [10]:
# 4. 数据特征的构造
df.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

In [11]:
df['sex'] = df['sex'].astype('category')

In [12]:
df['bill_radio'] = df['bill_length_mm'] / df['bill_depth_mm']

In [13]:
df.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_radio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.090909
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270115
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.238889
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.901554
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.907767

In [14]:
# 5. 数据分析
# 数据分箱：体重分为3个等级
labels = ['低', '中', '高']
df['body_level'] = pd.cut(df['body_mass_g'], bins=3, labels=labels)

In [15]:
df['body_level'].value_counts()

body_level
低    150
中    128
高     55
Name: count, dtype: int64

In [16]:
# 分组：按岛屿和性别分组分析
df.groupby(['sex'], observed=False).agg({
    'body_mass_g': ['mean', 'median', 'count']
})

        body_mass_g
               mean  median count
sex
Female  3862.272727  3650.0   165
Male    4545.684524  4300.0   168

In [17]:
df.groupby(['island'], observed=False).agg({
    'body_mass_g': ['mean', 'median', 'count']
})

           body_mass_g
                  mean  median count
island
Biscoe     4719.171779  4800.0   163
Dream      3718.902439  3700.0   123
Torgersen  3708.510638  3700.0    47